### ISSUE TITLE
Core packages with same name generated in both lib and lib64

### ISSUE THREAD

**Issue by nikonikolov** [ros-infrastructure/catkin_pkg#153] opened 2016-10-11 23:44 UTC
I don't know whether this is the right place to submit this issue. 

I installed ROS from source on Slackware Linux. However for most of the packages it generated python modules with the same name in both `~/ros_catkin_ws/install_isolated/lib/python2.7/site-packages` and `~/ros_catkin_ws/install_isolated/lib64/python2.7/site-packages`. This is a problem because this creates name clashes and causes import errors. For example, currently these are some of the actionlib modules:

```
~/ros_catkin_ws/install_isolated/lib64/python2.7/site-packages/actionlib/__init__.py
~/ros_catkin_ws/install_isolated/lib64/python2.7/site-packages/actionlib/exceptions.py
~/ros_catkin_ws/install_isolated/lib/python2.7/site-packages/actionlib/msg/__init__.py
```

My `$PYTHONPATH` includes both

```
~/ros_catkin_ws/install_isolated/lib64/python2.7/site-packages
~/ros_catkin_ws/install_isolated/lib/python2.7/site-packages
```

However, because of the name clash of the actionlib module, python only finds the module under the `lib64` directory and the one under `lib` is ignored. Thus `import actionlib.execptions` works ok, but `import actionlib.msg` fails. When I paste the `msg` directory in the same directory as `exceptions.py`, everything works fine.

There are other modules which have the same problem. Why are the modules split in such a way and how can I fix this? To my knowledge, python does not work like that and it does not expect the same module to be in both `lib` and `lib64`. For comparison, building from source on Ubuntu Xenial on a 64-bit VM placed everything under `lib`.

EDIT: A thing I noticed is that under modules in `lib` would only contain `msg` or `srv` folders or `__init__.py` files, while the corresponding directory in `lib64` would contain `.py` modules.

**Comment by gavanderhoorn** [comment] 2016-10-12 15:52
[Why ROS generates core packages with same name in both lib and lib64?](http://answers.ros.org/question/245437) on ROS Answers.

**Comment by dirk-thomas** [comment] 2016-10-13 23:04
`catkin_pkg` is a pure Python package and can't get built in a catkin workspace. Therefore it can't have the described problem. So I think this isn't the right place to report the problem.

If this is a problem affecting every package which contains Python code as well as messages / service then this might be a duplicate of this ticket (ros/catkin#632) which was filled for Gentoo.

**Closed** 2016-10-17 19:54 UTC

**Comment by nikonikolov** [comment] 2016-10-19 00:51
Sorry for the late response and for reporting to the wrong repo. It seems similar to the referenced issue but not exactly the same, so I will just submit this issue to catkin?

**Comment by tfoote** [comment] 2016-10-19 04:25
@nikonikolov please check out https://github.com/ros/catkin/pull/831 for a potential fix
