### ISSUE TITLE
[catkin_generate_changelog] UnicodeDecodeError: 'ascii' codec can't decode

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/catkin_pkg#179] opened 2017-06-03 01:36 UTC
You can replicate the issue by the following:

```
$ dpkg -p ros-indigo-catkin|grep Ver
Version: 0.6.19-0trusty-20170312-153241-0700
$ cd /tmp/moveit_kinetic                      
$ git clone https://github.com/ros-planning/moveit.git
Cloning into 'moveit'...
remote: Counting objects: 68429, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 68429 (delta 0), reused 2 (delta 0), pack-reused 68420
Receiving objects: 100% (68429/68429), 51.83 MiB | 8.96 MiB/s, done.
Resolving deltas: 100% (37116/37116), done.
Checking connectivity... done.
$ cd moveit/
$ ls
LICENSE.txt       moveit_experimental  moveit_ros              README.md
moveit            moveit_kinematics    moveit.rosinstall
moveit_commander  moveit_planners      moveit_runtime
moveit_core       moveit_plugins       moveit_setup_assistant
$ git branch -vv
* kinetic-devel 3a7a98a [origin/kinetic-devel] Merge pull request #515 from mintar/ikfast_c++11
$ catkin_generate_changelog                   
Found packages: chomp_motion_planner, moveit, moveit_commander, moveit_controller_manager_example, moveit_core, moveit_experimental, moveit_fake_controller_manager, moveit_kinemat
ics, moveit_planners, moveit_planners_chomp, moveit_planners_ompl, moveit_plugins, moveit_ros, moveit_ros_benchmarks, moveit_ros_control_interface, moveit_ros_manipulation, moveit
_ros_move_group, moveit_ros_perception, moveit_ros_planning, moveit_ros_planning_interface, moveit_ros_robot_interaction, moveit_ros_visualization, moveit_ros_warehouse, moveit_ru
ntime, moveit_setup_assistant, moveit_simple_controller_manager
Querying commit information since latest tag...
Traceback (most recent call last):
  File "/usr/bin/catkin_generate_changelog", line 9, in <module>
    load_entry_point('catkin-pkg==0.3.4', 'console_scripts', 'catkin_generate_changelog')()
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/cli/generate_changelog.py", line 120, in main_catching_runtime_error
    main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/cli/generate_changelog.py", line 104, in main
    tag2log_entries = get_forthcoming_changes(vcs_client, skip_merges=args.skip_merges)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/changelog_generator.py", line 82, in get_forthcoming_changes
    from_tag=from_tag.name, to_tag=to_tag.name, skip_merges=skip_merges)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/changelog_generator_vcs.py", line 208, in get_log_entries
    log_entries.append(LogEntry(msg, affected_paths, self._get_author(hash_)))
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/changelog_generator_vcs.py", line 143, in _get_author
    result = self._run_command(cmd)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/changelog_generator_vcs.py", line 100, in _run_command
    result['output'] = output.rstrip().decode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 8: ordinal not in range(128)
$ git log
commit 3a7a98aea3a09d4ecca08340a47c6aaf746959f4
Merge: f36b720 357a884
Author: G.A. vd. Hoorn <g.a.vanderhoorn@tudelft.nl>
Date:   Thu Jun 1 11:19:08 2017 +0200

    Merge pull request #515 from mintar/ikfast_c++11
    
    ikfast_kinematics_plugin: Add c++11 compile option
```

**Comment by dirk-thomas** [comment] 2017-06-03 01:40
Duplicate of #177.

**Closed by dirk-thomas** 2017-06-03 01:40 UTC

**Comment by 130s** [comment] 2017-06-03 02:14
I think I'll still report here since all necessary info is already there.

I thought #178 resolved this issue but after processing some files the program terminates with the following error, and I see `moveit_experimental/CHANGELOG.rst` gets overwritten with size-0 file after the program exits.

```
$ cd /home/rosnoodle/ROS/ncws/src/ros-infrastructure/catkin_pkg
$ git checkout fix_encode_decode_error
$ git log
 
commit 352e7f8675343682050f4be1f4a97819ca2012f0
Author: Dirk Thomas <dirk-thomas@users.noreply.github.com>
Date:   Fri Jun 2 08:54:38 2017 -0700

    fix encode/decode problems

$ export PYTHONPATH=/home/rosnoodle/ROS/ncws/src/ros-infrastructure/catkin_pkg/src:$PYTHONPATH 
$ export PYTHONPATH=/home/rosnoodle/ROS/ncws/src/ros-infrastructure/catkin_pkg/src/catkin_pkg:$PYTHONPATH 
$ export PYTHONPATH=/home/rosnoodle/ROS/ncws/src/ros-infrastructure/catkin_pkg/bin:$PYTHONPATH 
$ export PATH=/home/rosnoodle/ROS/ncws/src/ros-infrastructure/catkin_pkg/bin:$PATH
$ /tmp/moveit_k
$ which catkin_generate_changelog
/home/rosnoodle/ROS/ncws/src/ros-infrastructure/catkin_pkg/bin/catkin_generate_changelog
$ /home/rosnoodle/ROS/ncws/src/ros-infrastructure/catkin_pkg/bin/catkin_generate_changelog
Found packages: chomp_motion_planner, moveit, moveit_commander, moveit_controller_manager_example, moveit_core, moveit_experimental, moveit_fake_controller_manager, moveit_kinematics, moveit_planners, moveit_planners_chomp, moveit_planners_ompl, moveit_plugins, moveit_ros, moveit_ros_benchmarks, moveit_ros_control_interface, moveit_ros_manipulation, moveit_ros_move_group, moveit_ros_perception, moveit_ros_planning, moveit_ros_planning_interface, moveit_ros_robot_interaction, moveit_ros_visualization, moveit_ros_warehouse, moveit_runtime, moveit_setup_assistant, moveit_simple_controller_manager
Querying commit information since latest tag...
Updating forthcoming section of changelog files...
- updating 'moveit_plugins/moveit_ros_control_interface/CHANGELOG.rst'
- updating 'moveit_plugins/moveit_controller_manager_example/CHANGELOG.rst'
- updating 'moveit_plugins/moveit_fake_controller_manager/CHANGELOG.rst'
- updating 'moveit_runtime/CHANGELOG.rst'
- updating 'moveit_ros/perception/CHANGELOG.rst'
- updating 'moveit_experimental/CHANGELOG.rst'
Traceback (most recent call last):
  File "/home/rosnoodle/ROS/ncws/src/ros-infrastructure/catkin_pkg/bin/catkin_generate_changelog", line 8, in <module>
    sys.exit(main_catching_runtime_error())
  File "/home/rosnoodle/ROS/ncws/src/ros-infrastructure/catkin_pkg/src/catkin_pkg/cli/generate_changelog.py", line 120, in main_catching_runtime_error
    main(*args, **kwargs)
  File "/home/rosnoodle/ROS/ncws/src/ros-infrastructure/catkin_pkg/src/catkin_pkg/cli/generate_changelog.py", line 113, in main
    update_changelogs(base_path, packages_with, tag2log_entries, logger=logging, vcs_client=vcs_client, skip_contributors=args.skip_contributors)
  File "/home/rosnoodle/ROS/ncws/src/ros-infrastructure/catkin_pkg/src/catkin_pkg/changelog_generator.py", line 126, in update_changelogs
    f.write(data.encode('utf-8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3576: ordinal not in range(128)
```

**Comment by dirk-thomas** [comment] 2017-06-05 18:02
Please see the latest update of #178.
