### ISSUE TITLE
invalid XML: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by berkaydeniz** [ros-infrastructure/catkin_pkg#234] opened 2018-08-09 04:03 UTC
The main reason why I am creating this issue is that what I have looks like this:
https://github.com/ros-infrastructure/rosdep/issues/309

I have been working on a PR on ROS installation on macOS: https://github.com/mikepurvis/ros-install-osx/pull/126 which means I have been doing installations over and over as I have been addressing small things here and there and writing a walkthrough. Out of nowhere, as of an hour ago I started having this problem:

```
ERROR: Rosdep experienced an error: [/Users/deniz/ros-install-osx/melodic_desktop_full_ws/src/roslisp/manifest.xml] invalid XML: 'ascii' codec can't encode character u'\xf6' in position 213: ordinal not in range(128)
Please go to the rosdep page [1] and file a bug report with the stack trace below.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.12.2

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/rosdep2/main.py", line 140, in rosdep_main
    exit_code = _rosdep_main(args)
  File "/usr/local/lib/python2.7/site-packages/rosdep2/main.py", line 388, in _rosdep_main
    return _package_args_handler(command, parser, options, args)
  File "/usr/local/lib/python2.7/site-packages/rosdep2/main.py", line 484, in _package_args_handler
    return command_handlers[command](lookup, packages, options)
  File "/usr/local/lib/python2.7/site-packages/rosdep2/main.py", line 682, in command_install
    uninstalled, errors = installer.get_uninstalled(packages, implicit=options.recursive, verbose=options.verbose)
  File "/usr/local/lib/python2.7/site-packages/rosdep2/installers.py", line 445, in get_uninstalled
    resolutions, errors = self.lookup.resolve_all(resources, installer_context, implicit=implicit)
  File "/usr/local/lib/python2.7/site-packages/rosdep2/lookup.py", line 393, in resolve_all
    rosdep_keys = self.get_rosdeps(resource_name, implicit=implicit)
  File "/usr/local/lib/python2.7/site-packages/rosdep2/lookup.py", line 315, in get_rosdeps
    return self.loader.get_rosdeps(resource_name, implicit=implicit)
  File "/usr/local/lib/python2.7/site-packages/rosdep2/rospkg_loader.py", line 138, in get_rosdeps
    if resource_name in self.get_catkin_paths():
  File "/usr/local/lib/python2.7/site-packages/rosdep2/rospkg_loader.py", line 127, in get_catkin_paths
    self._catkin_packages_cache = dict(find_catkin_paths(self._rospack))
  File "/usr/local/lib/python2.7/site-packages/rosdep2/rospkg_loader.py", line 126, in find_catkin_paths
    filter(lambda x: src.get_manifest(x).is_catkin, src.list()))
  File "/usr/local/lib/python2.7/site-packages/rosdep2/rospkg_loader.py", line 126, in <lambda>
    filter(lambda x: src.get_manifest(x).is_catkin, src.list()))
  File "/usr/local/lib/python2.7/site-packages/rospkg/rospack.py", line 167, in get_manifest
    return self._load_manifest(name)
  File "/usr/local/lib/python2.7/site-packages/rospkg/rospack.py", line 211, in _load_manifest
    retval = self._manifests[name] = parse_manifest_file(self.get_path(name), self._manifest_name, rospack=self)
  File "/usr/local/lib/python2.7/site-packages/rospkg/manifest.py", line 434, in parse_manifest_file
    return parse_manifest(manifest_name, f.read().decode('utf-8'), filename)
  File "/usr/local/lib/python2.7/site-packages/rospkg/manifest.py", line 454, in parse_manifest
    raise InvalidManifest("[%s] invalid XML: %s" % (filename, e))
InvalidManifest: [/Users/deniz/ros-install-osx/melodic_desktop_full_ws/src/roslisp/manifest.xml] invalid XML: 'ascii' codec can't encode character u'\xf6' in position 213: ordinal not in range(128)
```

this was not happening yesterday, so I'm wondering if it has something to do with the latest release: https://github.com/ros-infrastructure/catkin_pkg/releases/tag/0.4.8

**Comment by dirk-thomas** [comment] 2018-08-09 20:24
Duplicate of ros-infrastructure/rospkg#154.

**Closed by dirk-thomas** 2018-08-09 20:24 UTC
